[package]
name = "dvote-rs-ffi"
version = "0.7.0"
authors = ["Jør∂¡ <itsbrickpop@gmail.com>"]
edition = "2018"

[lib]
name = "dvotesnarks"
crate-type = ["staticlib", "cdylib"]

[dependencies]
za-prover = { git = "https://github.com/adria0/za", rev = "e3634a3" }
